<?php

return [
    'source_list_name' => '',
    'email_template_name' => '',
    'email_sending_enabled' => false,
    'mail_webhook_secret' => '',
    'mail_api_enabled' => false,
    'mail_api_url' => 'https://mail01.mail.anesda.de/mailcontrol/v1/outbound/messages',
    'mail_api_key' => '',
    'mail_api_tenant_id' => 0,
    'mail_api_account_id' => 0,
    'lock_minutes' => 20,
    'default_callback_days' => 7,
    'callback_escalation_days' => 2,
    'external_stale_days' => 14,
    'max_attempts' => 5,
    'retry_days' => [2, 4, 7, 14, 30],
    'candidate_batch_size' => 200,
    'candidate_scan_limit' => 5000,
    'local_postcode_patterns' => [],
    'positive_patterns' => [],
    'exclude_patterns' => [],
    // Diese Muster werden sowohl in PHP als auch mit MariaDB REGEXP verwendet
    // und enthalten deshalb bewusst keine Regex-Begrenzer oder Flags.
    'central_retail_name_pattern' => '^(edeka|e[ -]?center|marktkauf|nah[[:space:]]*&[[:space:]]*gut|netto[[:space:]]+marken-discount|aldi|lidl|kaufland|rewe|penny|norma|globus[[:space:]]+baumarkt|toom[[:space:]]+baumarkt|obi([[:space:]]+markt)?|hagebau(markt)?|dm[[:space:]]+drogerie([[:space:]]+markt)?|rossmann|müller[[:space:]]+drogerie|tedox|kik|tedi|action|jysk|dänisches[[:space:]]+bettenlager|deichmann|fressnapf|mediamarkt|saturn)([^[:alnum:]]|$)',
    'school_pattern' => '(^|[^[:alnum:]])(schule|grundschule|oberschule|gesamtschule|gymnasium|berufsschule|förderschule|volkshochschule)([^[:alnum:]]|$)',
    'small_business_pattern' => '(^|[^[:alnum:]])(ergotherapie|ergotherapeut|ergo[ -]?praxis|physiotherapie|logopädie|logopaedie|podologie|heilpraktiker|psychotherapie|hebamme|massagepraxis)([^[:alnum:]]|$)',
    'medium_business_pattern' => '(^|[^[:alnum:]])(gmbh|mbh|ug[[:space:]]*\\(haftungsbeschränkt\\)|ohg|kg|e\\.?[[:space:]]*k\\.?|genossenschaft|maschinenbau|anlagenbau|metallbau|stahlbau|werkzeugbau|elektrotechnik|automation|automatisierung|ingenieur(büro|gesellschaft)|systemhaus|softwarehaus|it-service|logistik|spedition|produktion|industrie|fertigung|bauunternehmen|autohaus|druckerei|verlag|hotel|pflegeheim|wohnungsbau|immobilienverwaltung)([^[:alnum:]]|$)',
    'linkedin_discovery_enabled' => true,
    'linkedin_discovery_search_endpoint' => 'https://www.google.com/search',
    'linkedin_discovery_timeout_seconds' => 5,
    'linkedin_discovery_cache_days' => 30,
    'linkedin_discovery_max_results' => 5,
    'dialer_android_store_url' => 'https://play.google.com/store/apps/details?id=de.anesda.crmspeedphone.dialer',
    'dialer_ios_store_url' => 'https://apps.apple.com/app/id6794342212',
    'pbx_enabled' => false,
    // Als Argumentliste, damit keine Shell-Auswertung stattfindet. Zugangsdaten gehören in config.local.php.
    'pbx_gateway_command' => [],
    'pbx_ami_host' => '',
    'pbx_ami_port' => 5038,
    'pbx_ami_username' => '',
    'pbx_ami_secret' => '',
    'pbx_ami_context' => 'from-internal',
    'pbx_ami_timeout_seconds' => 10,
];
